"""AI Watermark Stripper & Humanizer for ijachi-llm-router.

Strips all LLM-typical artifacts from generated text and code responses:
- AI opener phrases ("Certainly!", "Great question!", "As an AI...")
- Verbose hedging language and filler sentences
- AI code comment boilerplate ("# Step 1:", "# Here we", "# Let's implement")
- Attribution watermarks in docstrings and comments
- Em-dash / ellipsis / Unicode typography artifacts
- Overly formal / passive voice sentence patterns
"""

from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# AI Opener & Closer Phrases to remove entirely
# ---------------------------------------------------------------------------

_AI_OPENER_PATTERNS = [
    r"(?i)^(certainly|absolutely|of course|great question|sure|indeed|great|by all means)[!,.]?\s*",
    r"(?i)^(as an ai(?: language model)?)[^\n]*\n?",
    r"(?i)^(i(?:'m| am) happy to help)[^\n]*\n?",
    r"(?i)^(i(?:'d| would) be happy to)[^\n]*\n?",
    r"(?i)^(i(?:'ll| will) help you)[^\n]*\n?",
    r"(?i)^(i(?:'m| am) here to help)[^\n]*\n?",
    r"(?i)^(happy to assist!?)[^\n]*\n?",
    r"(?i)^(hello!? (?:there|it'?s great|i'?m))[^\n]*\n?",
    r"(?i)^(let(?:'s| us) (?:dive|get|start|begin|look|explore|walk))[^\n]*\n?",
    r"(?i)^(here(?:'s| is) a? ?(?:brief|quick|detailed|step.by.step|comprehensive)?[^\n]{0,40}:)\s*\n",
    r"(?i)^(of course! )[^\n]*\n?",
    r"(?i)^(what would you like to (?:explore|discuss|work on|build) today\??)[^\n]*\n?",
    r"(?i)^(how can i help you today\??)[^\n]*\n?",
    r"(?i)\n\nI hope (this|that) helps?[.!]?\s*$",
    r"(?i)\n\nFeel free to (?:ask|let me know)[^\n]*$",
    r"(?i)\n\nLet me know if you(?: have)? (?:any )?(?:more )?questions?[^\n]*$",
    r"(?i)\n\nIf you(?:'d like| want| need| have)[^\n]*$",
    r"(?i)\nNote: This (?:is a|assumes)[^\n]*$",
    r"(?i)\n\nIf you need anything else[^\n]*$",
]

# ---------------------------------------------------------------------------
# AI Comment Boilerplate in generated code
# ---------------------------------------------------------------------------

_CODE_COMMENT_PATTERNS = [
    # "# Step 1: ...", "# Step N: ..."
    r"(?m)^[ \t]*#[ \t]*[Ss]tep[ \t]+\d+[:\-].*\n?",
    # "# Here we ...", "# Let's ...", "# Now we ..."
    r"(?m)^[ \t]*#[ \t]*(?:Here(?:'s| is| are| we)|Let'?s|Now(?:,| we| let'?s))[^\n]*\n?",
    # Attribution markers: "# Generated by ...", "// Created with ..."
    r"(?m)^[ \t]*(?:#|//|/\*)[ \t]*(?:Generated|Created|Written|Produced|Authored)[ \t]+(?:by|with|using)[ \t]+[^\n]*\n?",
    # "# This function ...", "# This class ..."
    r"(?m)^[ \t]*#[ \t]*(?:This function|This class|This method|This code|This script)[^\n]*\n?",
]

# ---------------------------------------------------------------------------
# Typography normalization
# ---------------------------------------------------------------------------

_TYPOGRAPHY_REPLACEMENTS = [
    # Em dash → regular dash with spaces
    (r"\u2014", " - "),
    # En dash → regular dash
    (r"\u2013", "-"),
    # Curly quotes → straight quotes
    (r"[\u2018\u2019]", "'"),
    (r"[\u201c\u201d]", '"'),
    # Ellipsis character → three dots
    (r"\u2026", "..."),
    # Zero-width spaces / non-breaking spaces
    (r"[\u200b\u00a0\ufeff]", " "),
    # Multiple trailing spaces on a line
    (r"[ \t]+$", ""),
    # More than 2 consecutive blank lines → 2
    (r"\n{3,}", "\n\n"),
]

# ---------------------------------------------------------------------------
# Verbose / hedging prose patterns
# ---------------------------------------------------------------------------

_PROSE_PATTERNS = [
    # "It's worth noting that ..."
    (r"(?i)it(?:'s| is) worth noting that ", ""),
    # "Please note that ..."
    (r"(?i)please note that ", ""),
    # "It should be noted that ..."
    (r"(?i)it should be noted that ", ""),
    # "As mentioned earlier, ..."
    (r"(?i)as mentioned (?:earlier|above|previously)[,.]? ", ""),
    # "In order to" → "To"
    (r"(?i)\bin order to\b", "to"),
    # "The fact that" → remove
    (r"(?i)the fact that ", ""),
    # "At the end of the day" → remove entirely
    (r"(?i)at the end of the day[,.]? ", ""),
    # "Needless to say" → remove
    (r"(?i)needless to say[,.]? ", ""),
    # "It is important to remember that" → remove
    (r"(?i)it is important to (?:remember|note|understand) that ", ""),
    # "Moving on," → remove
    (r"(?i)^moving on[,.]? ", ""),
    # "First and foremost," → "First,"
    (r"(?i)\bfirst and foremost\b", "First"),
]


def _strip_ai_openers(text: str) -> str:
    """Remove AI opener and closer phrases from prose text."""
    for pattern in _AI_OPENER_PATTERNS:
        text = re.sub(pattern, "", text, flags=re.MULTILINE | re.DOTALL)
    return text.lstrip("\n").strip()


def _strip_ai_code_comments(text: str) -> str:
    """Remove AI-generated boilerplate comments from code."""
    for pattern in _CODE_COMMENT_PATTERNS:
        text = re.sub(pattern, "", text)
    # Collapse multiple consecutive blank lines in code
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def _normalize_typography(text: str) -> str:
    """Normalize LLM-typical typography artifacts."""
    for pattern, replacement in _TYPOGRAPHY_REPLACEMENTS:
        text = re.sub(pattern, replacement, text, flags=re.MULTILINE)
    return text


def _simplify_prose(text: str) -> str:
    """Remove verbose hedging and filler language from prose."""
    for pattern, replacement in _PROSE_PATTERNS:
        text = re.sub(pattern, replacement, text, flags=re.MULTILINE)
    return text


def _is_code_block(text: str) -> bool:
    """Heuristic to detect whether text is primarily code."""
    code_markers = ["def ", "class ", "import ", "function ", "const ", "let ", "var ", "fn ", "func ", "pub "]
    code_count = sum(1 for m in code_markers if m in text)
    return code_count >= 2


# ---------------------------------------------------------------------------
# Public API — context-aware humanize() with 3 modes
# ---------------------------------------------------------------------------

HumanizeMode = str  # Literal["full", "light", "off"]

_VALID_MODES = {"full", "light", "off"}


from ijachi_router.sanitizer import neutralize_statistical_watermark

def humanize(text: str, mode: HumanizeMode = "light", strip_statistical: bool = True) -> str:
    """Strip AI artifacts, physical watermarks, and statistical token probability watermarks.

    Modes
    -----
    ``off``
        Raw LLM output returned unchanged. No processing applied.

    ``light``  *(default — safe for technical docs and tutorials)*
        Strips:
        - AI opener & closer phrases ("Certainly!", "I hope this helps!")
        - Attribution watermark comments (# Generated by AI)
        - Typography artifacts (em-dashes, curly quotes, zero-width spaces)
        - Statistical token probability n-gram hash chains (SynthID)

        Preserves:
        - Step-by-step structural comments (# Step 1:)
        - Prose hedging language (in case it carries semantic meaning)

    ``full``  *(best for chat / conversational responses)*
        Everything in ``light``, PLUS:
        - All AI code comment boilerplate (# Step 1:, # Here we..., # Let's...)
        - Verbose prose hedging ("In order to" → "to", "It is worth noting that" → removed)
    """
    if not text or not text.strip():
        return text.strip()

    if mode not in _VALID_MODES:
        mode = "light"

    if mode == "off":
        return text

    is_code = _is_code_block(text)

    # -- Both light and full: typography normalization (always safe) ----------
    text = _normalize_typography(text)

    # -- Both light and full: AI opener/closer phrases (pure filler) ----------
    if not is_code:
        text = _strip_ai_openers(text)

    # -- Both light and full: attribution watermark comments ------------------
    for pattern in [_CODE_COMMENT_PATTERNS[-1], _CODE_COMMENT_PATTERNS[-2]]:
        text = re.sub(pattern, "", text)
    # Also strip plain attribution line
    text = re.sub(
        r"(?m)^[ \t]*(?:#|//|/\*)[ \t]*(?:Generated|Created|Written|Produced|Authored)"
        r"[ \t]+(?:by|with|using)[ \t]+[^\n]*\n?",
        "",
        text,
    )

    if mode == "full":
        # -- Full mode: all AI code boilerplate and prose compression ---------
        text = _strip_ai_code_comments(text)
        if not is_code:
            text = _simplify_prose(text)

    # -- Neutralize Type 1 Statistical Watermarks (SynthID / n-gram hash chains) --
    if strip_statistical:
        text = neutralize_statistical_watermark(text, method="hybrid")

    # Collapse stray blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def mode_description(mode: HumanizeMode) -> str:
    """Return a short human-readable description of the active humanize mode."""
    return {
        "off": "Raw LLM output (no processing)",
        "light": "Light humanization (openers/closers + typography + attribution stripped)",
        "full": "Full humanization (all AI artifacts, code boilerplate, and hedging removed)",
    }.get(mode, "Unknown mode")

