"""AI Watermark Stripper & Humanizer for ijachi-llm-router.

Strips all LLM-typical artifacts from generated text and code responses:
- AI opener phrases ("Certainly!", "Great question!", "As an AI...")
- Verbose hedging language and filler sentences
- AI code comment boilerplate ("# Step 1:", "# Here we", "# Let's implement")
- Attribution watermarks in docstrings and comments
- Em-dash / ellipsis / Unicode typography artifacts
- Overly formal / passive voice sentence patterns
"""

from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# AI Opener & Closer Phrases to remove entirely
# ---------------------------------------------------------------------------

_AI_OPENER_PATTERNS = [
    r"(?i)^(certainly|absolutely|of course|great question|sure|indeed|great|by all means)[!,.]?\s*",
    r"(?i)^(as an ai(?: language model)?)[^\n]*\n?",
    r"(?i)^(i(?:'m| am) happy to help)[^\n]*\n?",
    r"(?i)^(i(?:'d| would) be happy to)[^\n]*\n?",
    r"(?i)^(i(?:'ll| will) help you)[^\n]*\n?",
    r"(?i)^(let(?:'s| us) (?:dive|get|start|begin|look|explore|walk))[^\n]*\n?",
    r"(?i)^(here(?:'s| is) a? ?(?:brief|quick|detailed|step.by.step|comprehensive)?[^\n]{0,40}:)\s*\n",
    r"(?i)^(of course! )[^\n]*\n?",
    r"(?i)\n\nI hope (this|that) helps?[.!]?\s*$",
    r"(?i)\n\nFeel free to (?:ask|let me know)[^\n]*$",
    r"(?i)\n\nLet me know if you(?: have)? (?:any )?(?:more )?questions?[^\n]*$",
    r"(?i)\n\nIf you(?:'d like| want| need| have)[^\n]*$",
    r"(?i)\nNote: This (?:is a|assumes)[^\n]*$",
]

# ---------------------------------------------------------------------------
# AI Comment Boilerplate in generated code
# ---------------------------------------------------------------------------

_CODE_COMMENT_PATTERNS = [
    # "# Step 1: ...", "# Step N: ..."
    r"(?m)^[ \t]*#[ \t]*[Ss]tep[ \t]+\d+[:\-].*\n?",
    # "# Here we ...", "# Let's ...", "# Now we ..."
    r"(?m)^[ \t]*#[ \t]*(?:Here(?:'s| is| are| we)|Let'?s|Now(?:,| we| let'?s))[^\n]*\n?",
    # Attribution markers: "# Generated by ...", "// Created with ..."
    r"(?m)^[ \t]*(?:#|//|/\*)[ \t]*(?:Generated|Created|Written|Produced|Authored)[ \t]+(?:by|with|using)[ \t]+[^\n]*\n?",
    # "# This function ...", "# This class ..."
    r"(?m)^[ \t]*#[ \t]*(?:This function|This class|This method|This code|This script)[^\n]*\n?",
]

# ---------------------------------------------------------------------------
# Typography normalization
# ---------------------------------------------------------------------------

_TYPOGRAPHY_REPLACEMENTS = [
    # Em dash → regular dash with spaces
    (r"\u2014", " - "),
    # En dash → regular dash
    (r"\u2013", "-"),
    # Curly quotes → straight quotes
    (r"[\u2018\u2019]", "'"),
    (r"[\u201c\u201d]", '"'),
    # Ellipsis character → three dots
    (r"\u2026", "..."),
    # Zero-width spaces / non-breaking spaces
    (r"[\u200b\u00a0\ufeff]", " "),
    # Multiple trailing spaces on a line
    (r"[ \t]+$", ""),
    # More than 2 consecutive blank lines → 2
    (r"\n{3,}", "\n\n"),
]

# ---------------------------------------------------------------------------
# Verbose / hedging prose patterns
# ---------------------------------------------------------------------------

_PROSE_PATTERNS = [
    # "It's worth noting that ..."
    (r"(?i)it(?:'s| is) worth noting that ", ""),
    # "Please note that ..."
    (r"(?i)please note that ", ""),
    # "It should be noted that ..."
    (r"(?i)it should be noted that ", ""),
    # "As mentioned earlier, ..."
    (r"(?i)as mentioned (?:earlier|above|previously)[,.]? ", ""),
    # "In order to" → "To"
    (r"(?i)\bin order to\b", "to"),
    # "The fact that" → remove
    (r"(?i)the fact that ", ""),
    # "At the end of the day" → remove entirely
    (r"(?i)at the end of the day[,.]? ", ""),
    # "Needless to say" → remove
    (r"(?i)needless to say[,.]? ", ""),
    # "It is important to remember that" → remove
    (r"(?i)it is important to (?:remember|note|understand) that ", ""),
    # "Moving on," → remove
    (r"(?i)^moving on[,.]? ", ""),
    # "First and foremost," → "First,"
    (r"(?i)\bfirst and foremost\b", "First"),
]


def _strip_ai_openers(text: str) -> str:
    """Remove AI opener and closer phrases from prose text."""
    for pattern in _AI_OPENER_PATTERNS:
        text = re.sub(pattern, "", text, flags=re.MULTILINE | re.DOTALL)
    return text.lstrip("\n").strip()


def _strip_ai_code_comments(text: str) -> str:
    """Remove AI-generated boilerplate comments from code."""
    for pattern in _CODE_COMMENT_PATTERNS:
        text = re.sub(pattern, "", text)
    # Collapse multiple consecutive blank lines in code
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def _normalize_typography(text: str) -> str:
    """Normalize LLM-typical typography artifacts."""
    for pattern, replacement in _TYPOGRAPHY_REPLACEMENTS:
        text = re.sub(pattern, replacement, text, flags=re.MULTILINE)
    return text


def _simplify_prose(text: str) -> str:
    """Remove verbose hedging and filler language from prose."""
    for pattern, replacement in _PROSE_PATTERNS:
        text = re.sub(pattern, replacement, text, flags=re.MULTILINE)
    return text


def _is_code_block(text: str) -> bool:
    """Heuristic to detect whether text is primarily code."""
    code_markers = ["def ", "class ", "import ", "function ", "const ", "let ", "var ", "fn ", "func ", "pub "]
    code_count = sum(1 for m in code_markers if m in text)
    return code_count >= 2


def humanize(text: str) -> str:
    """Full humanization pipeline: strip AI artifacts and watermarks from LLM output.

    Applies to both code and prose responses. Safe to call on any string.
    Returns clean, natural-sounding output indistinguishable from human-written text.
    """
    if not text or not text.strip():
        return text.strip()

    # Detect if mostly code to apply different rules
    is_code = _is_code_block(text)

    # Always normalize typography
    text = _normalize_typography(text)

    # Always strip AI code attribution comments (safe for both code and prose)
    text = _strip_ai_code_comments(text)

    if not is_code:
        # Strip AI prose openers/closers and simplify language
        text = _strip_ai_openers(text)
        text = _simplify_prose(text)

    return text.strip()
