"""Tests for Humanizer, Security Scanner, and Zero-Regression Validator."""

from __future__ import annotations

import pytest

from ijachi_router.humanizer import humanize
from ijachi_router.security import scan, scan_and_fix, format_security_summary
from ijachi_router.validator import validate, _validate_python, _check_python_imports


# ---------------------------------------------------------------------------
# Humanizer tests
# ---------------------------------------------------------------------------

class TestHumanizer:

    def test_strips_certainly_opener(self):
        text = "Certainly! Here is how you do it:\n\nThe answer is 42."
        result = humanize(text)
        assert "Certainly" not in result
        assert "42" in result

    def test_strips_as_an_ai(self):
        text = "As an AI language model, I cannot provide personal opinions.\nBut here are the facts."
        result = humanize(text)
        assert "As an AI" not in result
        assert "facts" in result

    def test_strips_happy_to_help(self):
        text = "I'd be happy to help you with that!\nThe function is called `sort()`."
        result = humanize(text)
        assert "happy to help" not in result
        assert "sort()" in result

    def test_strips_closing_phrase(self):
        text = "The answer is Python.\n\nI hope this helps!"
        result = humanize(text)
        assert "I hope this helps" not in result

    def test_strips_feel_free_closer(self):
        text = "Use `os.path.join()`.\n\nFeel free to ask if you have more questions."
        result = humanize(text)
        assert "Feel free" not in result

    def test_em_dash_normalized(self):
        text = "This is great\u2014really great."
        result = humanize(text)
        assert "\u2014" not in result
        assert "-" in result

    def test_strips_ai_code_comments(self):
        code = "# Step 1: Initialize the router\nrouter = Router()\n# Here we build the result\nresult = router.route(prompt)"
        result = humanize(code)
        assert "Step 1:" not in result
        assert "router = Router()" in result

    def test_preserves_real_content(self):
        text = "Use `hashlib.sha256()` instead of MD5 for security reasons."
        result = humanize(text)
        assert "sha256" in result
        assert "MD5" in result

    def test_simplifies_in_order_to(self):
        text = "In order to start the server, run the command below."
        result = humanize(text)
        assert "In order to" not in result
        assert "to" in result

    def test_strips_attribution_watermark(self):
        code = "# Generated by Claude 3.7 Sonnet\ndef main():\n    pass"
        result = humanize(code)
        assert "Generated by" not in result
        assert "def main" in result

    def test_empty_string_safe(self):
        assert humanize("") == ""
        assert humanize("   ") == ""


# ---------------------------------------------------------------------------
# Security Scanner tests
# ---------------------------------------------------------------------------

class TestSecurityScanner:

    def test_detects_eval(self):
        code = "result = eval(user_input)"
        report = scan(code)
        categories = {i.category for i in report.issues}
        assert "Code Injection" in categories

    def test_detects_hardcoded_secret(self):
        code = 'api_key = "sk-1234567890abcdef"'
        report = scan(code)
        categories = {i.category for i in report.issues}
        assert "Secrets Exposure" in categories

    def test_detects_md5(self):
        code = "digest = hashlib.md5(data).hexdigest()"
        report = scan(code)
        categories = {i.category for i in report.issues}
        assert "Weak Cryptography" in categories

    def test_auto_fixes_md5_to_sha256(self):
        code = "digest = hashlib.md5(data).hexdigest()"
        fixed, issues = scan_and_fix(code)
        assert "hashlib.sha256(" in fixed
        assert "hashlib.md5(" not in fixed

    def test_auto_fixes_yaml_unsafe_load(self):
        code = "data = yaml.load(stream)"
        fixed, issues = scan_and_fix(code)
        assert "yaml.safe_load" in fixed

    def test_auto_fixes_debug_true(self):
        code = "DEBUG = True"
        fixed, issues = scan_and_fix(code)
        assert "DEBUG = False" in fixed

    def test_detects_pickle_loads(self):
        code = "obj = pickle.loads(data)"
        report = scan(code)
        categories = {i.category for i in report.issues}
        assert "Unsafe Deserialization" in categories

    def test_detects_shell_injection(self):
        code = "subprocess.run(cmd, shell=True)"
        report = scan(code)
        categories = {i.category for i in report.issues}
        assert "Injection" in categories

    def test_clean_code_is_safe(self):
        code = "def add(a: int, b: int) -> int:\n    return a + b\n"
        report = scan(code)
        assert report.is_safe is True
        assert len(report.issues) == 0

    def test_format_summary_no_issues(self):
        code = "x = 1 + 2"
        report = scan(code)
        summary = format_security_summary(report)
        assert "No security vulnerabilities" in summary


# ---------------------------------------------------------------------------
# Validator tests
# ---------------------------------------------------------------------------

class TestValidator:

    def test_valid_python_passes(self):
        code = "def hello(name: str) -> str:\n    return f'Hello, {name}!'\n"
        result = validate(code, filename="hello.py")
        assert result.valid is True
        assert len(result.errors) == 0

    def test_invalid_python_blocked(self):
        code = "def broken(\n    print('oops')"
        result = validate(code, filename="broken.py")
        assert result.valid is False
        assert len(result.errors) > 0
        assert "SyntaxError" in result.errors[0]

    def test_non_python_file_skips_compile(self):
        code = "SELECT * FROM users WHERE id = ?;"
        result = validate(code, filename="query.sql")
        # No Python compile attempted — should pass
        assert result.valid is True

    def test_summary_for_valid(self):
        code = "x = 42\n"
        result = validate(code, filename="x.py")
        assert "passed" in result.summary()

    def test_summary_for_invalid(self):
        code = "def bad syntax:\n"
        result = validate(code, filename="bad.py")
        assert "failed" in result.summary().lower() or not result.valid
